when:
  - event: push
  - event: manual

labels:
  backend: docker

steps:
  - name: test
    image: rust:1-alpine
    commands:
      - cargo test

  - name: demo
    image: rust:1-alpine
    commands:
      - cargo run --release --bin=demo